dont forget to source the environment

source <venv>/bin/activate

In [2]:
import numpy as np
from skimage import io
import skimage
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

!echo "np,io,plt and more imported, let's move on"
print(skimage.__version__, matplotlib.__version__, widgets.__version__)

np,io,plt and more imported, let's move on
0.24.0 3.9.2 8.1.5


In [3]:
a = np.random.randint(-10,10, (7,2))

In [4]:
a = np.array([1,2,3,8])
print(f"a={a}")
print(f"dimension of a is {a.ndim} and shape = {a.shape} where elements are {a.dtype}")
print(f"a consumes {a.nbytes} bytes of memory")

a=[1 2 3 8]
dimension of a is 1 and shape = (4,) where elements are int64
a consumes 32 bytes of memory


In [5]:
#  observe that only the one element of the array is float

B = np.array([[3,1,4],[1,2.,5]])
print(f"B={B}")
print(f"dimension of a is {B.ndim} and shape = {B.shape} where elements are {B.dtype}")
print(f"B consumes {B.nbytes} bytes of memory")

B=[[3. 1. 4.]
 [1. 2. 5.]]
dimension of a is 2 and shape = (2, 3) where elements are float64
B consumes 48 bytes of memory


In [6]:
# what if I just bytes
c = np.array ([1,2,3,8],dtype="int8")
print(f"c= {c}")
print(f"dimension of a is {c.ndim} and shape = {c.shape} where elements are {c.dtype}")
print(f"c consumes {c.nbytes} bytes of memory")

c= [1 2 3 8]
dimension of a is 1 and shape = (4,) where elements are int8
c consumes 4 bytes of memory


it is possible to get help from jupyter using 
?something_python

In [ ]:
# note that you can get a help as follows just by running this cell:
?a.transpose
# check out the help tab on the right (I presume)

In case you need to get help inline try the following:
print (something_python.__doc__)

In [9]:
print(a.transpose.__doc__)

a.transpose(*axes)

    Returns a view of the array with axes transposed.

    Refer to `numpy.transpose` for full documentation.

    Parameters
    ----------
    axes : None, tuple of ints, or `n` ints

     * None or no argument: reverses the order of the axes.

     * tuple of ints: `i` in the `j`-th place in the tuple means that the
       array's `i`-th axis becomes the transposed array's `j`-th axis.

     * `n` ints: same as an n-tuple of the same ints (this form is
       intended simply as a "convenience" alternative to the tuple form).

    Returns
    -------
    p : ndarray
        View of the array with its axes suitably permuted.

    See Also
    --------
    transpose : Equivalent function.
    ndarray.T : Array property returning the array transposed.
    ndarray.reshape : Give a new shape to an array without changing its data.

    Examples
    --------
    >>> import numpy as np
    >>> a = np.array([[1, 2], [3, 4]])
    >>> a
    array([[1, 2],
           [3, 4]])

In [10]:
# for larger 2D array

D = np.array([[1,2,3,4,5,6,7,8,9],[11,22,33,44,55,66,77,88,99]])
print(D)

# get the first element
print(f"first element of d= {D[0,0]}")
# get the last element
print (f'last element of d = {D[1,8]}')
# however, do we have to know the lenght of the array to get the last element
# rmemeber that python supports negative indexing
print(f"last element of d= {D[-1,-1]}")

[[ 1  2  3  4  5  6  7  8  9]
 [11 22 33 44 55 66 77 88 99]]
first element of d= 1
last element of d = 99
last element of d= 99


In [11]:
# get the first row
D[0,:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# get the 3rd column
D[:,2]

array([ 3, 33])

In [13]:
# observe the shapes of these slices
print(f'shape of {D[0,:]} is {D[0,:].shape}')
print(f'shape of {D[:,2]} is {D[:,2].shape}')

shape of [1 2 3 4 5 6 7 8 9] is (9,)
shape of [ 3 33] is (2,)


In [14]:
# get the 2x3 matrix from the center of the array D
D[:,3:6]

array([[ 4,  5,  6],
       [44, 55, 66]])

In [15]:
# now lets print every other element on the second row  of D
D [1,0: : 2]

array([11, 33, 55, 77, 99])

In [82]:
# print second line backwards
print(D)
print(f"second row of D backwards is: {D[1, -1::-1]}")

print('\nThis did not really work did it? Where is the first element on row 2?\nFix the line above and try again')

[[ 1  2  3  4  5  6  7  8  9]
 [11 22 33 44 55 66 77 88 99]]
second row of D backwards is: [99 88 77 66 55 44 33 22 11]

This did not really work did it? Where is the first element on row 2?
Fix the line above and try again


In [84]:
A = np.array([[1,2,3],[3,2,8],[5,3,1]])
A < 3

array([[ True,  True, False],
       [False,  True, False],
       [False, False,  True]])

In [85]:
A = np.array([[1,2,3],[3,2,8],[5,3,1]])
A[ A< 3]

array([1, 2, 2, 1])

In [87]:
D = np.array ([[1,2,3,4,5,6,7,8,9],[11,22,33,44,55,66,77,88,99]])
print (D)
print ('elements of D that are on the second row and divisible by 3')
np.array([v for v in D[1,:] if v%3==0])

[[ 1  2  3  4  5  6  7  8  9]
 [11 22 33 44 55 66 77 88 99]]
elements of D that are on the second row and divisible by 3


array([33, 66, 99])

In [88]:
D[1,D [1,:]%3==0]

array([33, 66, 99])

In [89]:
D = np.array([[1,2,3,4,5,6,7,8,9],[11,22,33,44,55,66,77,88,99]])
print(D)
print('\nselected elements with indices 0,1,5 from first, 2,3 from second rows:')
D[[0,0,0,1,1],[0,1,5,2,3]]

[[ 1  2  3  4  5  6  7  8  9]
 [11 22 33 44 55 66 77 88 99]]

selected elements with indices 0,1,5 from first, 2,3 from second rows:


array([ 1,  2,  6, 33, 44])