dont forget to source the environment

 source .venv/bin/activate

In [1]:
import numpy as np
from skimage import io
import skimage
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

!echo "np,io,plt and more imported, let's move on"
print(skimage.__version__, matplotlib.__version__, widgets.__version__)

np,io,plt and more imported, let's move on
0.24.0 3.9.2 8.1.5


In [2]:
a = np.random.randint(-10,10, (7,2))

In [3]:
a = np.array([1,2,3,8])
print(f"a={a}")
print(f"dimension of a is {a.ndim} and shape = {a.shape} where elements are {a.dtype}")
print(f"a consumes {a.nbytes} bytes of memory")

a=[1 2 3 8]
dimension of a is 1 and shape = (4,) where elements are int64
a consumes 32 bytes of memory


In [4]:
#  observe that only the one element of the array is float

B = np.array([[3,1,4],[1,2.,5]])
print(f"B={B}")
print(f"dimension of a is {B.ndim} and shape = {B.shape} where elements are {B.dtype}")
print(f"B consumes {B.nbytes} bytes of memory")

B=[[3. 1. 4.]
 [1. 2. 5.]]
dimension of a is 2 and shape = (2, 3) where elements are float64
B consumes 48 bytes of memory


In [5]:
# what if I just bytes
c = np.array ([1,2,3,8],dtype="int8")
print(f"c= {c}")
print(f"dimension of a is {c.ndim} and shape = {c.shape} where elements are {c.dtype}")
print(f"c consumes {c.nbytes} bytes of memory")

c= [1 2 3 8]
dimension of a is 1 and shape = (4,) where elements are int8
c consumes 4 bytes of memory


it is possible to get help from jupyter using 
?something_python

In [6]:
# note that you can get a help as follows just by running this cell:
?a.transpose
# check out the help tab on the right (I presume)

Docstring:
a.transpose(*axes)

Returns a view of the array with axes transposed.

Refer to `numpy.transpose` for full documentation.

Parameters
----------
axes : None, tuple of ints, or `n` ints

 * None or no argument: reverses the order of the axes.

 * tuple of ints: `i` in the `j`-th place in the tuple means that the
   array's `i`-th axis becomes the transposed array's `j`-th axis.

 * `n` ints: same as an n-tuple of the same ints (this form is
   intended simply as a "convenience" alternative to the tuple form).

Returns
-------
p : ndarray
    View of the array with its axes suitably permuted.

See Also
--------
transpose : Equivalent function.
ndarray.T : Array property returning the array transposed.
ndarray.reshape : Give a new shape to an array without changing its data.

Examples
--------
>>> import numpy as np
>>> a = np.array([[1, 2], [3, 4]])
>>> a
array([[1, 2],
       [3, 4]])
>>> a.transpose()
array([[1, 3],
       [2, 4]])
>>> a.transpose((1, 0))
array([[1, 3],
    

In case you need to get help inline try the following:
print (something_python.__doc__)

In [7]:
print(a.transpose.__doc__)

a.transpose(*axes)

    Returns a view of the array with axes transposed.

    Refer to `numpy.transpose` for full documentation.

    Parameters
    ----------
    axes : None, tuple of ints, or `n` ints

     * None or no argument: reverses the order of the axes.

     * tuple of ints: `i` in the `j`-th place in the tuple means that the
       array's `i`-th axis becomes the transposed array's `j`-th axis.

     * `n` ints: same as an n-tuple of the same ints (this form is
       intended simply as a "convenience" alternative to the tuple form).

    Returns
    -------
    p : ndarray
        View of the array with its axes suitably permuted.

    See Also
    --------
    transpose : Equivalent function.
    ndarray.T : Array property returning the array transposed.
    ndarray.reshape : Give a new shape to an array without changing its data.

    Examples
    --------
    >>> import numpy as np
    >>> a = np.array([[1, 2], [3, 4]])
    >>> a
    array([[1, 2],
           [3, 4]])

In [8]:
# for larger 2D array

D = np.array([[1,2,3,4,5,6,7,8,9],[11,22,33,44,55,66,77,88,99]])
print(D)

# get the first element
print(f"first element of d= {D[0,0]}")
# get the last element
print (f'last element of d = {D[1,8]}')
# however, do we have to know the lenght of the array to get the last element
# rmemeber that python supports negative indexing
print(f"last element of d= {D[-1,-1]}")

[[ 1  2  3  4  5  6  7  8  9]
 [11 22 33 44 55 66 77 88 99]]
first element of d= 1
last element of d = 99
last element of d= 99


In [9]:
# get the first row
D[0,:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# get the 3rd column
D[:,2]

array([ 3, 33])

In [11]:
# observe the shapes of these slices
print(f'shape of {D[0,:]} is {D[0,:].shape}')
print(f'shape of {D[:,2]} is {D[:,2].shape}')

shape of [1 2 3 4 5 6 7 8 9] is (9,)
shape of [ 3 33] is (2,)


In [12]:
# get the 2x3 matrix from the center of the array D
D[:,3:6]

array([[ 4,  5,  6],
       [44, 55, 66]])

In [13]:
# now lets print every other element on the second row  of D
D [1,0: : 2]

array([11, 33, 55, 77, 99])

In [14]:
# print second line backwards
print(D)
print(f"second row of D backwards is: {D[1, -1::-1]}")

print('\nThis did not really work did it? Where is the first element on row 2?\nFix the line above and try again')

[[ 1  2  3  4  5  6  7  8  9]
 [11 22 33 44 55 66 77 88 99]]
second row of D backwards is: [99 88 77 66 55 44 33 22 11]

This did not really work did it? Where is the first element on row 2?
Fix the line above and try again


In [15]:
A = np.array([[1,2,3],[3,2,8],[5,3,1]])
A < 3

array([[ True,  True, False],
       [False,  True, False],
       [False, False,  True]])

In [16]:
A = np.array([[1,2,3],[3,2,8],[5,3,1]])
A[ A< 3]

array([1, 2, 2, 1])

In [17]:
D = np.array ([[1,2,3,4,5,6,7,8,9],[11,22,33,44,55,66,77,88,99]])
print (D)
print ('elements of D that are on the second row and divisible by 3')
np.array([v for v in D[1,:] if v%3==0])

[[ 1  2  3  4  5  6  7  8  9]
 [11 22 33 44 55 66 77 88 99]]
elements of D that are on the second row and divisible by 3


array([33, 66, 99])

In [18]:
D[1,D [1,:]%3==0]

array([33, 66, 99])

In [19]:
D = np.array([[1,2,3,4,5,6,7,8,9],[11,22,33,44,55,66,77,88,99]])
print(D)
print('\nselected elements with indices 0,1,5 from first, 2,3 from second rows:')
D[[0,0,0,1,1],[0,1,5,2,3]]

[[ 1  2  3  4  5  6  7  8  9]
 [11 22 33 44 55 66 77 88 99]]

selected elements with indices 0,1,5 from first, 2,3 from second rows:


array([ 1,  2,  6, 33, 44])

In [20]:
# iteration directly over np.array

Z = np.array([[1,2,3],[4,5,6]])
for elind,elval in enumerate(Z):
    print(f"element{elind}in Z is: {elval}")

element0in Z is: [1 2 3]
element1in Z is: [4 5 6]


Short answer is: iterating over multidimensional array is not a good idea, and apperantly indexing is not like Matlab. So be careful. Yet, note that in numpy you will not need for loops over arrays most of the time. Continue to understand why...

In [23]:
shape1= (2,3)
shape2= (3,3)
shape3= (2,4)
full_value =15

print(f"{shape1} array full of zeros:\n{np.zeros(shape1)}\n")
print(f"{shape2} array full of ones:\n{np.ones(shape2)}\n")
print(f"{shape3} array full of {full_value}s:\n {np.full(shape3,15)}\n")
# an alternative way for full function
print(f"{shape3} array full of {full_value}s:\n {np.ones(shape3)*full_value}\n")

(2, 3) array full of zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

(3, 3) array full of ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

(2, 4) array full of 15s:
 [[15 15 15 15]
 [15 15 15 15]]

(2, 4) array full of 15s:
 [[15. 15. 15. 15.]
 [15. 15. 15. 15.]]



In [25]:
# random valued array
print(np.random.rand())
print(np.random.rand(3,5))
print(np.random.randint(10,size=(2,3)))


0.33708721241127293
[[0.73684006 0.90709181 0.79586784 0.24526153 0.36103334]
 [0.52290421 0.59834503 0.49279389 0.19661453 0.46379371]
 [0.89529231 0.24152515 0.62924052 0.33950391 0.3922216 ]]
[[7 6 9]
 [6 2 4]]


In [30]:
def MatPrint(M,message = 'Matrix:'):
    '''
    this function accepts a variable M, expected to be in the form of np.array
    and prints it more like a matrix
    Potential future work:
        digit size is currently fixed to 8, therefore it will not show arrays with long numbers properly
    '''
    try:
        if M.ndim != 2: # this function is meant to print only 2D arrays, if not 2D just print it
            print(message)
            print(M)
        else:
            print(message)
            spc = ' '
            sep = '|'
            for r in M: # go over each row, i.e. 1 and 2 :)
                res = sep + spc
                for d in r: # go over each element in the current row
                    res = res+ '{:8.2f}'.format(d) + spc
                res = res + sep
                print(res)
    except:
        print(f"Is {M} really a meaningful numpy array?")

this function can be improved

download following file the current folder 
Next import function of interest from the downloaded function.
to test run a docstring (the help document)

Note that you can read the content of the donwloaded files. Check out the files icon at the bottom on the left side.

Just double click on the file you want to view and also edit.

In [33]:
!rm bug_numpy_utils.py
!wget https://raw.githubusercontent.com/bugrakoku/bug_python_utils/main/bug_numpy_utils.py
from bug_numpy_utils import MatPrint,CData # note that once these files are downloaded you can read their content.
# print function's help after import

print(MatPrint.__doc__)

--2024-10-05 22:34:37--  https://raw.githubusercontent.com/bugrakoku/bug_python_utils/main/bug_numpy_utils.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18456 (18K) [text/plain]
Saving to: ‘bug_numpy_utils.py’

bug_numpy_utils.py  100%[===================>]  18.02K  --.-KB/s    in 0.007s  

2024-10-05 22:34:38 (2.53 MB/s) - ‘bug_numpy_utils.py’ saved [18456/18456]



ModuleNotFoundError: No module named 'sklearn'